import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";

export default function Home() {

  const handleOnBtnClick = ()=>{
    console.log("H1! Banner button")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner handleOnClick={handleOnBtnClick} buttonText="View stores nearby"/>
        <Image className={styles.heroImage} src="/static/hero-image.png" width={700} height={400}/>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
